# Generated by Django 3.1.1 on 2020-09-30 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_videos_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='django_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
