# Generated by Django 3.1.1 on 2020-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userss_django_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videos',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
