# Generated by Django 3.1.1 on 2020-11-11 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_videos_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
