# Generated by Django 3.1.1 on 2020-11-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_videos_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
