# Generated by Django 3.1.1 on 2020-11-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201114_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userss')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.videos')),
            ],
        ),
    ]
