# Generated by Django 3.1.1 on 2020-11-17 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='watch_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
