# Generated by Django 3.1.1 on 2020-11-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_watchhistory_watch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='banner_image_url',
            field=models.CharField(default='http://127.0.0.1:8000/media/default_banner.jpg', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userss',
            name='profile_pic_url',
            field=models.CharField(default='http://127.0.0.1:8000/media/default-profile-picture.jpg', max_length=500, null=True),
        ),
    ]
