# Generated by Django 3.1.1 on 2020-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201123_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='channel_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
